### ISSUE TITLE
[Fedora] Finding Targets by Name Error

### ISSUE THREAD

**Issue by JPGlaser** [KeplerGO/K2fov#12] opened 2016-01-20 17:29 UTC
Hey All,
I just started using this tool to begin working on finding targets for my planned K2 proposal and have ran into a snag. Everytime I try to run the following command, regardless of the object chosen, I get the following result:

```
$ K2findCampaigns-byname -p "Hyades"
Traceback (most recent call last):
  File "/home/jglaser/anaconda/bin/K2findCampaigns-byname", line 6, in <module>
    sys.exit(K2findCampaigns_byname_main())
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/K2fov/K2findCampaigns.py", line 135, in K2findCampaigns_byname_main
    campaigns, ra, dec = findCampaignsByName(targetname)
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/K2fov/K2findCampaigns.py", line 74, in findCampaignsByName
    'for target "{0}".'.format(target))
ValueError: Could not find coordinates for target "Hyades".
```

Any ideas on why this is occurring?

~ Joe G.

**Comment by barentsen** [comment] 2016-01-20 18:46
Thank you for reporting this, @JPGlaser.

The problem is that the name resolving service takes ages to reply at  the moment (i.e. the web call to `http://cdsweb.u-strasbg.fr/cgi-bin/nph-sesame/A?Hyades` is very slow)

I have increased the timeout to 90 seconds now (bcd7c89), so if you re-install the latest master version of K2fov from GitHub things should work again (but be very slow).  I am going to assume that this will resolve itself soon.  If not, we'll have to get in touch with CDS who run the name resolving web service.

**Comment by barentsen** [comment] 2016-01-21 04:05
Still very slow.  I've notified CDS now.

**Comment by barentsen** [comment] 2016-01-21 15:17
CDS has fixed the problem. Should work fine again now!

**Closed as completed by barentsen** 2016-01-21 15:17 UTC

**Comment by JPGlaser** [comment] 2016-01-21 21:20
Thanks for the quick fix, @barentsen. It seems that the Hyades is still listed as not being on silicon for K2 which is weird considering it should be in Campaign 4 as well as 13. Testing out M9 does retrieve the correct campaign, but the plotting function seems to be failing. Any ideas?

~ Joe G. 

```
$ K2findCampaigns-byname -p "M9"
Success! M9 is on silicon during K2 campaigns [11].
Writing K2findCampaigns.png
Traceback (most recent call last):
  File "/home/jglaser/anaconda/bin/K2findCampaigns-byname", line 6, in <module>
    sys.exit(K2findCampaigns_byname_main())
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/K2fov/K2findCampaigns.py", line 147, in K2findCampaigns_byname_main
    save_context_plots(ra, dec, targetname=targetname)
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/K2fov/K2findCampaigns.py", line 83, in save_context_plots
    myplot = plot.create_context_plot(ra, dec, name=targetname)
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/K2fov/plot.py", line 138, in create_context_plot
    plot.plot_ecliptic()
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/K2fov/plot.py", line 112, in plot_ecliptic
    unit="deg", frame="barycentrictrueecliptic").icrs
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/coordinates/sky_coordinate.py", line 134, in __init__
    kwargs = self._parse_inputs(args, kwargs)
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/coordinates/sky_coordinate.py", line 199, in _parse_inputs
    frame = valid_kwargs['frame'] = _get_frame(args, kwargs)
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/coordinates/sky_coordinate.py", line 777, in _get_frame
    frame_cls = _get_frame_class(frame)
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/coordinates/sky_coordinate.py", line 750, in _get_frame_class
    .format(frame, sorted(frame_names)))
ValueError: Coordinate frame barycentrictrueecliptic not in allowed values ['fk4', 'fk4noeterms', 'fk5', 'galactic', 'icrs']
```

**Comment by barentsen** [comment] 2016-01-21 22:18
@JPGlaser The error message is due to the fact that you are using a version of AstroPy older than v1.1 (which is quite normal because v1.1 was only released last month).  I'm going to change this so that it works with older versions of AstroPy, but if you want a quick fix then upgrade AstroPy.

The position of the Hyades as given by the name resolving service (~`04:26:54 +15:52:04`) is indeed not on silicon, but of course the cluster is very big and many of its members are.

**Comment by barentsen** [comment] 2016-01-22 00:47
@JPGlaser If you install the latest version from GitHub, it will no longer crash and just skip plotting the ecliptic plane if only an older version of AstroPy is available.  Again, thx for reporting this.

**Comment by JPGlaser** [comment] 2016-01-27 16:54
@barentsen, thanks for the help. I ran a pip upgrade on AstroPy as well as K2fov and am returning the following error. Sorry to keep coming back to you on this, but having this tool up and running would drastically reduce writing time for the K2 campaign 11, 12, & 13 proposals.

```
$ K2findCampaigns-byname "T Tauri"
Traceback (most recent call last):
  File "/home/jglaser/anaconda/bin/K2findCampaigns-byname", line 6, in <module>
    sys.exit(K2findCampaigns_byname_main())
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/K2fov/K2findCampaigns.py", line 135, in K2findCampaigns_byname_main
    campaigns, ra, dec = findCampaignsByName(targetname)
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/K2fov/K2findCampaigns.py", line 64, in findCampaignsByName
    from astropy.coordinates import SkyCoord
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/coordinates/__init__.py", line 13, in <module>
    from .baseframe import *
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/coordinates/baseframe.py", line 1181, in <module>
    from .earth import EarthLocation
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/coordinates/earth.py", line 11, in <module>
    from .builtin_frames import ITRS
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/__init__.py", line 28, in <module>
    from .fk5 import FK5
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/fk5.py", line 10, in <module>
    from .. import earth_orientation as earth
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/coordinates/earth_orientation.py", line 19, in <module>
    jd1950 = Time('B1950', scale='tai').jd
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/time/core.py", line 220, in __init__
    self._init_from_vals(val, val2, format, scale, copy)
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/time/core.py", line 262, in _init_from_vals
    self._time = self._get_time_fmt(val, val2, format, scale)
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/time/core.py", line 306, in _get_time_fmt
    raise ValueError('Input values did not match {0}'.format(err_msg))
ValueError: Input values did not match any of the formats where the format keyword is optional [u'datetime', u'iso', u'isot', u'yday', u'fits', u'byear_str', u'jyear_str']
```

**Comment by barentsen** [comment] 2016-01-27 17:40
@JPGlaser Interesting.  I'm unable to reproduce this.

Can you do me a favor and try running:
`python -c "from astropy.coordinates import SkyCoord"`
to see if that works correctly?

**Comment by barentsen** [comment] 2016-01-27 17:49
@JPGlaser This looks like an obscure issue with AstroPy and/or numpy (discussed here: https://github.com/astropy/astropy/issues/3237).

It looks like others have been able to solve this by either re-installing AstroPy and Numpy, or if AstroPy was installed from GitHub, running `git clean -fxd` before re-installing.

**Comment by JPGlaser** [comment] 2016-01-27 18:34
@barentsen Yeah not sure what is going on here. Using pip uninstall and then pip install on the two packages seems to not have solved the error.

```
[jglaser@localhost ~]$ python -c "from astropy.coordinates import SkyCoord"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/coordinates/__init__.py", line 13, in <module>
    from .baseframe import *
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/coordinates/baseframe.py", line 1181, in <module>
    from .earth import EarthLocation
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/coordinates/earth.py", line 11, in <module>
    from .builtin_frames import ITRS
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/__init__.py", line 28, in <module>
    from .fk5 import FK5
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/fk5.py", line 10, in <module>
    from .. import earth_orientation as earth
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/coordinates/earth_orientation.py", line 19, in <module>
    jd1950 = Time('B1950', scale='tai').jd
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/time/core.py", line 220, in __init__
    self._init_from_vals(val, val2, format, scale, copy)
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/time/core.py", line 262, in _init_from_vals
    self._time = self._get_time_fmt(val, val2, format, scale)
  File "/home/jglaser/anaconda/lib/python2.7/site-packages/astropy/time/core.py", line 306, in _get_time_fmt
    raise ValueError('Input values did not match {0}'.format(err_msg))
ValueError: Input values did not match any of the formats where the format keyword is optional [u'datetime', u'iso', u'isot', u'yday', u'fits', u'byear_str', u'jyear_str']
```

**Comment by barentsen** [comment] 2016-01-27 19:16
@JPGlaser `pip uninstall` doesn't usually remove everything.  I would recommend that you do this:

```
rm -rf /home/jglaser/anaconda/lib/python2.7/site-packages/astropy
```

and then re-install using either `conda install astropy` or `pip install astropy`.

This problem is described in a bit more detail in AstroPy's list of known issues here: http://docs.astropy.org/en/stable/known_issues.html#creating-a-time-object-fails-with-valueerror-after-upgrading-astropy

**Comment by JPGlaser** [comment] 2016-01-27 20:04
@barentsen Alright, got it working just fine by doing the above and running conda install astropy. I also installed it on our RedHat cluster and its working fine as well.

However, I am getting this small error that you might want to know about:

```
[jglaser@localhost ~]$ K2findCampaigns-byname -p "M9"
Success! M9 is on silicon during K2 campaigns [11].
Writing K2findCampaigns.png
/home/jglaser/anaconda/lib/python2.7/site-packages/matplotlib/collections.py:571: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):
Writing K2findCampaigns-zoom.png
```

**Comment by barentsen** [comment] 2016-01-27 21:31
@JPGlaser Thanks for reporting this.  This is a warning message that originates from within `matplotlib` and appears to go away when one updates matplotlib from v1.4 to v1.5.
